version: '3'

services:
  app:
    image: shan/python-echo:1.0
    stdin_open: true
    tty: true
    entrypoint: /bin/sh
    volumes:
      - /home/sneha/PycharmProjects/unsupervised-clir/Embeddings:/usr/src/app/Embeddings
      - /home/sneha/PycharmProjects/unsupervised-clir/Data:/usr/src/app/Data
